### ISSUE TITLE
Query one day of data at a time

### ISSUE THREAD

**Issue by brettgriffin** [fleet-data/source-itunes-reporter#12]
Running the task for one day usually inserts records for two separate dates:

Querying for `2017-07-31 00:00:00`  returns data for `2017-07-31 00:00:00` and `2017-08-01 00:00:00`.

**Comment by jre247** [comment]
@brettgriffin what's the status on this? Did we determine that Itunes UI Export produces data with multiple days?

**Comment by jre247** [comment]
@brettgriffin do you know how I can log in to itunes reporter UI again and do an export? I'll verify if this issue is also in the export, and not just java. Thanks.
