### ISSUE TITLE
Suspicious code block iterating rows/columns

### ISSUE THREAD

**Issue by brettgriffin** [fleet-data/source-itunes-reporter#7]
The following code block is suspicious. I'm opening this issue to investigate this.
```
row.forEach((rowKey, rowValue) -> {
	for (ColumnMetadata column : schema.Columns) {
	    if (!rowColumnMapping.containsKey(column.Name))
	        rowFormatted.put(column.Name, null);
	    else
	        rowFormatted.put(rowKey, rowValue);
	};

});
```

At the very least, `rowKey` and `rowValue` should be renamed `columnKey` and `columnValue` respectively. The each represent a COLUMN in the current row.

The suspicious part of the code is that for each column in a row, the code iterates over each column in the schema and checks if that column is present in the mapping. If it is not, it adds the column to the rowsFormatted list with a null value. If the column does not exist, the code then puts the `rowKey` and `rowValue`.

I believe the correct way to rewrite this as follows:

```
row.forEach((columnKey, columnValue) -> {
    rowFormatted.put(columnKey, columnValue);
});

for (ColumnMetadata column : schema.Columns) {
    if (!rowFormatted.containsKey(column.Name))
        rowFormatted.put(column.Name, null);
}
```

This adds each column key/value to the mapping, and then, for any column that exists in the schema but not the current row, adds the column name and a null value.

**Comment by jre247** [comment]
fleet 0.0.90 has this fix.
